### ISSUE TITLE
Missing Pelorus chart README

### ISSUE THREAD

**Issue by jtudelag** [konveyor/pelorus#234]
Actually it would be pretty useful to have a README.md for the Pelorus chart, with all the configuration options documented there.

As an example, this [README](https://github.com/redhat-cop/helm-charts/blob/master/charts/jenkins/README.md) from the CoP Jenkins chart with all the configuration.

Currently, this information is spread over the documentation in a few places, and I would say it is not consistent nor complete:

- https://pelorus.readthedocs.io/en/latest/Install/
- https://pelorus.readthedocs.io/en/latest/Configuration/

Maybe we can even come up with some sort of modular docs that can be reused for Pelorus chart README and for the public docs, so only one piece has to be maintained.

**Comment by mpryc** [comment]
We do switch to the Opeator based installation. All supported by the operator options are now documented and available via docs:

- https://pelorus.readthedocs.io/en/latest/GettingStarted/configuration/PelorusCore/
- https://pelorus.readthedocs.io/en/latest/GettingStarted/configuration/ExporterDeploytime/
- https://pelorus.readthedocs.io/en/latest/GettingStarted/configuration/ExporterCommittime/
- https://pelorus.readthedocs.io/en/latest/GettingStarted/configuration/ExporterFailure/

We will be reviewing and removing unnecessary README files from the source code, so we have only one set of configuration options.

Also our operator uses openAPIV3Schema to define our options and best would be to auto-generate the docs from that part, but this isn't something this issue is for:
https://github.com/konveyor/pelorus/blob/master/pelorus-operator/config/crd/bases/charts.pelorus.konveyor.io_pelorus.yaml#L17


Closing as this is not relevant for the current operator.
