### ISSUE TITLE
Create an image with a common toolset that can be used across jobs

### ISSUE THREAD

**Issue by themoosman** [konveyor/pelorus#237]
Our helm charts use quite a few Kube jobs/cronjobs.  There is no consistency in the image used when the jobs use the same tools (curl, jq, etc).  This is creating tech debit across the charts.  

This issue is to create a common image with the tools needed to be used in all those jobs.

**Comment by KevinMGranger** [comment]
I completely agree. Some of the scripts we use are also a large mix of bash and jq and oc templating that makes it hard to read.

We should consider small python scripts to ease this pain point.

**Comment by mpryc** [comment]
We took different approach with the script(s) to install some of the common tools inside python virtual environment that is used for the development and as a base for CI systems.

We do pin some of the python dependencies, we do pin some of the executables, however not all of them should stay on the same version as having newer allows us to hit potential problems earlier.

I am closing this issue, because image is not required at this stage and we do have other approach, documented at:
  https://pelorus.readthedocs.io/en/latest/Development/#dev-environment-setup
