### ISSUE TITLE
Support custom certificates for any exporter that uses requests

### ISSUE THREAD

**Issue by KevinMGranger** [konveyor/pelorus#463]
The simplest approach is to allow mounting the CA trust file in the container, and then have the environment variable `REQUESTS_CA_BUNDLE` point to that path.

However, we must take care because [prepared requests do not take the environment into account](https://requests.readthedocs.io/en/latest/user/advanced/#:~:text=When%20you%20are,taken%20into%20account.). This is true even if you set the verify path on the session object.

It's also not clear if specifying this _overrides_ or _augments_ the CA bundles provided by `certifi`. That's risky to mix in a project that might reach out to public instances as well as private ones.

One solution that can handle both use cases: detect if a custom CA bundle is specified, and if so, append it to the CA bundle from `certifi` at container startup.

**Comment by jemerald** [comment]
As an alternative, could use the `ca.crt` attached to the service account - `/var/run/secrets/kubernetes.io/serviceaccount/ca.crt`

**Comment by mpryc** [comment]
@jemerald but the mentioned `/var/run/secrets/kubernetes.io/serviceaccount/ca.crt` is the cluster REST API certificate and not the one that exporter will use to communicate with the 3rd party service such as JIRA server ?

**Comment by jemerald** [comment]
@mpryc that is true. The `serviceaccount/ca.crt` would only guarantee access to the OpenShift cluster and not necessarily other servers.

**Comment by jemerald** [comment]
Another option I can think of, is to provide value override for the base image, so user can specify one with custom CA installed?

https://github.com/konveyor/pelorus/blob/master/charts/pelorus/charts/exporters/templates/_buildconfig.yaml#L27

**Comment by KevinMGranger** [comment]
@jemerald would mounting a volume containing the CA trust file and then specifying an env var pointing to it work?

**Comment by jemerald** [comment]
@KevinMGranger that could work too.

**Comment by mpryc** [comment]
So the issue is that self-signed SSL certificate for the REST APIs needs to be used by the python exporter which is running inside the pod to access external service, such as self-hosted JIRA instance or other self-hosted service. This is exactly #463, except it's a bit wider as not only for the JIRA exporter, but more generic for any type of the exporter to consume.

I will play with it, but my initial thought on that is we should allow to create per exporter ConfigMap with self-signed/custom CA-certificate from the REST API endpoint and use it in the python code to connect to the external service.

I am not convinced (yet) that adding custom/self-signed certificate to global cluster ca-bundle.crt is the right approach, as this will be available to all pods rather then only for the exporter which requires this certificate.

**Comment by KevinMGranger** [comment]
I agree that we shouldn't _prescribe_ using the cluster ca-bundle, but we could support it as an option.

**Comment by mpryc** [comment]
@KevinMGranger yep as an option it's feasible, we could even do:
1. Check if user deployed exporter with skip cert check option, if yes ignore SSL validation and skip point 2 and point 3
2. Check if configmap provided cert, try to use it
3. If point 2 fails or it's not defined use cluster cert

**Comment by KevinMGranger** [comment]
> It's also not clear if specifying this overrides or augments the CA bundles provided by certifi

I just verified this. It will override them, which means, for example:

- You have two projects tracked by committime.
- One is hosted on github.com,
- The other on some internal provider with a custom cert.

If you give a custom bundle, getting the first project will break, while the second one works.

Luckily, the library that requests uses, `certifi`, exposes its bundle! We could have a pre-processing step that appends both together, and then sets that file as the CA bundle.
