### ISSUE TITLE
Generic way to configure what's bug using config options for the github exporter

### ISSUE THREAD

**Issue by mpryc** [konveyor/pelorus#547]
More generic way to configure what's bug using config options would be nice to have as not all of the users may follow standard github labeling to measure issues with Pelorus

_Originally posted by @mpryc in https://github.com/konveyor/pelorus/issues/546#issuecomment-1180412452_

**Comment by weshayutin** [comment]
ah.. thanks for opening a new issue :)

**Comment by weshayutin** [comment]
@mpryc ah dang I was thinking about the k8s app label and github label

https://pelorus.readthedocs.io/en/latest/Configuration/

An example may be to override the APP_LABEL for the failure exporter to indicate a production bug or issue. The APP_LABEL with the value production_issue/name may give more context than app.kubernetes.io/name In this case the Github issue would be labeled with production_issue/name=todolist


So this bug is NOT resolved.  I would have to update..
https://github.com/konveyor/pelorus/blob/master/exporters/failure/collector_github.py#L125

and create a variable for what key word needs to be in the bug label.
I suppose in jira .. you have an issue w/ type bug so it's not a problem there.
I'm inclined to push this OUT of MVR.  WDYT?  I think we can create that change later.
